name: Core CI

on:
  push:
    branches:
      - main
      - next

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: ^1.17
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          args: --enable gofmt,govet,gocyclo,ineffassign,misspell
      - name: test
        run: go test -race -coverprofile=coverage.out
      - name: actions-goveralls
        uses: shogo82148/actions-goveralls@v1.6.0
        with:
          path-to-profile: coverage.out
